### ISSUE TITLE
Heroku Update

### ISSUE THREAD

**Issue by mrbenns** [stefansundin/rssbox#12]
How do I update to the latest version on my Heroku deployment?

**Comment by stefansundin** [comment]
I think there may be a way to deploy with the heroku cli, but I prefer deploying with git. Here's how I do it.

```
git clone git@github.com:stefansundin/rssbox.git
cd rssbox
git remote add heroku git@heroku.com:mrbennsrssbox.git
git push heroku master
```

Then later after I push more things, you can run this:
```
git pull
git push heroku master
```

**Comment by mrbenns** [comment]
Thank you again

S
