### ISSUE TITLE
Private Instagram Feeds?

### ISSUE THREAD

**Issue by mrbenns** [stefansundin/rssbox#17]
Is this even possible in the current framework? I would assume you would have to store login details somewhere?

**Comment by stefansundin** [comment]
Sorry for not responding for so long. It is possible to do this, but it is very hard to do, and I don't know if it will remain supported forever. It has broken a couple of times, and when it does, you might have to re-subscribe. I haven't tried this recently, so let me know if it still works at all.

The instructions are written in the code: https://github.com/stefansundin/rssbox/blob/3f45de2ff9d8db08b6fc98c28219d42a8c4355f7/app.rb#L544-L553

**Comment by eyoungmin** [comment]
https://github.com/stefansundin/rssbox/issues/21

**Comment by stefansundin** [comment]
The comment above no longer works. Right now you can self-host and set the `INSTAGRAM_SESSIONID` variable. This may change later (see #39).
