### ISSUE TITLE
Twitter update interval?

### ISSUE THREAD

**Issue by ODB88** [stefansundin/rssbox#24]
Hello,

I have a RSSBox instance running on the free plan on Heroku.

The first time I add a feed into Feedly it works great however after reading everything yesterday the feeds are no longer updating. 

Whats the default refresh time? Is it possible to modify it?

Thanks!

**Comment by stefansundin** [comment]
Hmm.. If you open the feed in your browser, do you see new entries that are not showing up in Feedly?

The app makes a new request to Twitter every time. I have no idea how often Feedly updates feeds. It may be configurable in there? I don't use Feedly, so I don't know for sure.

**Comment by stefansundin** [comment]
With the new caching code (#43), data from Twitter (and other services) is cached for a certain amount of time before it is fetched again.

If you self-host the app, you can change the duration here:

https://github.com/stefansundin/rssbox/blob/0ddc71357618d18c941bac9f779c6d0aa98c94de/app.rb#L167

The `60*60` means that a successful response from Twitter is cached for one hour. The next argument, `60`, means that errors are cached for 60 seconds before it is attempted again (e.g. Twitter if is down).
