### ISSUE TITLE
Autoplay Videos

### ISSUE THREAD

**Issue by Linkerss** [stefansundin/rssbox#26]
Hey Stefan, Is it possible to autoplay Twitter and Instagram videos but mute them?

Thank you

**Comment by stefansundin** [comment]
For Twitter, I believe so. You would need to add the `autoplay` and `muted` attributes to the video tag on this line: https://github.com/stefansundin/rssbox/blob/271e80b066b237c5db77e029a174a8b1a94ba48d/config/initializers/05-string.rb#L192

For Instagram, not as far as I know. I don't try to get the URL to the video file, so I just embed the whole post in case there is a video in it.

**Comment by Linkerss** [comment]
I have no experience with this. Could you do it for me on your App on my Heroku account?

Thank you

**Comment by Linkerss** [comment]
Stefan, How and where can I find that video line? Is it in your App? Or inside WP?

I've tried to change video attributes in WP Core files but it didn't work,

Thank you

**Comment by stefansundin** [comment]
As the code snippet explains, it is in the file `rssbox/config/initializers/05-string.rb` on line 192.

**Comment by Linkerss** [comment]
The thing is I'm not really sure how to get into rssbox config files. Could you please help?

I would like to add loop feature too if possible to have Gifs playing normally,

Thank you

**Comment by stefansundin** [comment]
You could make all of these changes on GitHub. First, you would need to fork the repository (use the fork button in the top right corner). Then, find the file and click the Edit button. Make the necessary changes.

Then, to deploy you would need to use a Terminal. In very broad terms, you would do the following:

1. First you would `git clone [...]` your fork.
2. Then you'd need to add your Heroku remote with `git remote add heroku [...]`.
3. Then, you would push your changes to the Heroku remote in order to deploy (`git push heroku master`).

**Comment by Linkerss** [comment]
Not really sure why you forcing users to do these things. I'm not a developer. I don't know how to do this.

I just ask for simple help and I respect your work and you as an App Author

**Comment by stefansundin** [comment]
I am not forcing you to do anything. You don't need to use the app if you don't want to. I have told you what steps you need to take to achieve your goal, but you can't expect me to perform these tasks for you.

**Comment by Linkerss** [comment]
Hey Stefan I made it. I'm so happy about it.

I did changes through Heroku.

Thank you so much :)

**Comment by Linkerss** [comment]
Stefan, Gifs and YouTube videos are still not able to do autoplays.

Any chance to change that?

Thank you

**Comment by stefansundin** [comment]
For YouTube, you need to add an `&autoplay=1` parameter to two places:
- https://github.com/stefansundin/rssbox/blob/271e80b066b237c5db77e029a174a8b1a94ba48d/config/initializers/05-string.rb#L146

Second place is only for YouTube feeds themselves, not sure if you use them, but here it is:
- https://github.com/stefansundin/rssbox/blob/3f45de2ff9d8db08b6fc98c28219d42a8c4355f7/views/youtube_feed.erb#L50

What gifs are you looking to add autoplay to?

**Comment by Linkerss** [comment]
Hey Stefan, YouTube autoplays are still not on even though I did everything you said.

I'm talking about Twitter Gifs autoplay. They seems to be short videos but somehow they still don't do autoplays after update,

Thank you
