### ISSUE TITLE
Website is overloaded

### ISSUE THREAD

**Issue by patrickdrd** [stefansundin/rssbox#28]
site rssbox.herokuapp.com has been going up and down constantly since yesteday night 

```
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
```

```
rssbox instagram is DOWN (https://rssbox.herokuapp.com/)
503 - Service Unavailable (The service is temporarily overloaded.)

```

**Comment by stefansundin** [comment]
Hi. I think the website is just overloaded at this point. I am using the free tier on Heroku, so it can only handle so much. I don't expect anything to change unless people start donating. I would suggest that you try hosting the app yourself, which should make it a lot more stable if you are the only user.

**Comment by stefansundin** [comment]
With the new caching code, response times are once again low / "normal". The website is finally usable again. Keep in mind that the website may be slow-ish once a day when Heroku restarts the dyno. This might be possible to mitigate by saving the cache between restarts somehow, but for now this is not super important to address.
