### ISSUE TITLE
The App is crashing

### ISSUE THREAD

**Issue by Linkerss** [stefansundin/rssbox#29]
Hey Stefan, Your App is crashing on my Heroku account. I wonder would you be kind to add autoplay, loop and mute features on your App for Twitter feeds and possibly Instagram feeds so I can move all my feeds to your Heroku App,

Thank you

**Comment by stefansundin** [comment]
Please try deploying the latest code, or copy-paste the specific error here.

**Comment by Linkerss** [comment]
I think I did everything you said but now even your Heroku App is crashing.

I think it might be due to Heroku Platform or some sort of caching issue since your App is working perfectly because once I try to update feeds manually it takes several attempts to catch the feeds :)

**Comment by stefansundin** [comment]
Try disabling URL resolution with `URL_RESOLUTION_DISABLED=true`. (make sure you are using the latest code)
