### ISSUE TITLE
Instagram Photo no found

### ISSUE THREAD

**Issue by eyoungmin** [stefansundin/rssbox#31]
I use content from instagram to publish in my other social media account automatically by using RSSBOX and IFTTT. but it seems doesn't work anymore. help me!

**Comment by stefansundin** [comment]
Hi there,

When you load your user in RSSBox, does it still show the RSS contents, or an error? Can you share your instagram handle?

I am not an expert in how IFTTT works, but does it show any kind of error message?

Thanks!

**Comment by eyoungmin** [comment]
![EK8WmNHWoAA0hmD](https://user-images.githubusercontent.com/21292037/70170066-5cf91f00-170f-11ea-9889-9ca49d2391c3.png)

Tweets are sent, but not photo was uploaded. 
A specific character is created in the image link.
`&amp;`

e.g)
https://scontent-gmp1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/76709220_481134295852515_3459881775019612135_n.jpg?_nc_ht=scontent-gmp1-1.cdninstagram.com**&amp;**_nc_cat=1**&amp;**oh=db0394661107e48ffb59ebe4e9e18065**&amp;**oe=5E7DDCB5

origin)
https://scontent-gmp1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/76709220_481134295852515_3459881775019612135_n.jpg?_nc_ht=scontent-gmp1-1.cdninstagram.com&_nc_cat=1&oh=db0394661107e48ffb59ebe4e9e18065&oe=5E7DDCB5

**Comment by stefansundin** [comment]
Hmm.. so the RSS feed encodes ampersands because that's how Atom feeds should encode them, and I think it does it properly. Maybe you can try to contact IFTTT and ask them if they are reading the RSS feed properly? I think they should expect `&amp;` to be in there and decode html entities.

Feel free to link them this issue thread and they can tell me that I'm wrong. :)

**Comment by Nick-Shannon** [comment]
Hi stefansundin & eyoungmin,  

Yes, I've the same problem.  The IFTTT applet for RSS to Twitter (with native photo) no longer works.  As discovered, the problem is the `&amp; ` . 

Let me know me know if you have any luck with IFTTT. 

RSSBox is great BTW.  Thanks stefansundin.

**Comment by eyoungmin** [comment]
I haven't received an answer yet.

**Comment by Nick-Shannon** [comment]
> I haven't received an answer yet.

Any news on this? Still doesn't work for me.

**Comment by eyoungmin** [comment]
> > I haven't received an answer yet.
> 
> Any news on this? Still doesn't work for me.

No, I haven't received an answer yet. There is the same problem with similar RSS services.
RSS-Bridge They haven't solved it, but there's a temporary solution. 
Many people have to keep talking about IFTTT.

**Comment by jutsh65** [comment]
I think this is a referer problem, not an issue with the img src url.

If I right click and load image in new tab (in Firefox) it loads fine. Checking the web tools network console for my RSS reader shows that the instagram images are returning a 200 code but only about 400 bytes. I've been doing some experiments with just creating an html page and putting the link in there with or without the &amp and I get the same result: a broken image.

I noticed that linkin.bio for artsy (https://linkin.bio/artsy) seems to be showing instagram thumbnails. But the code is difficult to understand. I am hopeful there is a parameter that can be added to the image url to allow at least a thumbnail, but still searching...
