### ISSUE TITLE
Could you add this website?

### ISSUE THREAD

**Issue by Franklin-24** [stefansundin/rssbox#37]
Hello, dear developer, I would like to subscribe to a website called BiliBili.Could you add this website(https://www.bilibili.com)?

**Comment by stefansundin** [comment]
Hi!

The websites that I support so far are websites that I use myself. I don't want to spend the time to implement and maintain a website that I don't use personally.

But I have tried to make RSS Box as easy as possible to modify and host yourself (for free). So please try to fork this repository, make the changes necessary, then deploy to your own Heroku instance. Then if you think your improvements would benefit more people, please submit a Pull Request and we can discuss if it's something I want to merge.

You need to find out if BiliBili has an API. Experiment and try to get the data necessary in the code. Pick an existing website that works in a similar way, then copy all of that code and try to change it to fit BiliBili.

Good luck!
