### ISSUE TITLE
It only shows one picture in Twitter feed

### ISSUE THREAD

**Issue by Marvinoo** [stefansundin/rssbox#45]
Hello sir, 
The service works great for twitter but I noticed that there's a bug or something that prevents the service from grabing more than 1 picture for any tweet that has multiple pictures in it. It means that any tweet with more than 1 picture only shows one picture (probably the first one) in the feed reader. 
The feed reader I use is : Feedbro for Firefox. 
Sorry for my English.

**Comment by stefansundin** [comment]
Hello.

Yes, I have noticed the same thing. I can't remember if it has always been like this. I have been meaning to fix it but I haven't had the time. Let's keep this issue open until I get a fix in. Thanks for reporting it.

**Comment by stefansundin** [comment]
This should now be fixed with 219cbfece9dab6d4c3b983ad41351fc8e535b4bb.
