### ISSUE TITLE
Heroku suspended my account

### ISSUE THREAD

**Issue by stefansundin** [stefansundin/rssbox#53]
I have no idea why, but Heroku suspended my account.

> Reason for suspension: violation of the [Heroku Acceptable Use Policy](https://www.heroku.com/policy/aup).

My guess is that Instagram lawyers sent a request to them to take it down. It would have been nice if they had asked me first since I would have removed the Instagram feature (it doesn't really work anyways). The reason why I suspect Instagram first is because of this: https://news.ycombinator.com/item?id=22209892

I emailed Heroku support to try to get some kind of answer. If this turns out to be the case then I may take preemptive steps to make this repository safer since I don't want to deal with any kind of DMCA situation here on GitHub.

Fucking Heroku, can't trust them. I had another app also running there, and they just shut everything down. Don't host anything important on their service. This is your official warning.

**Comment by stefansundin** [comment]
Great.. suspend my account on a Saturday morning and then don't be open for business to reply to my support request.

> Thank you for contacting Heroku Support! Your request has been received and will be reviewed by our support staff shortly.
> 
> Heroku business hours are 9am - 9pm Eastern Time, Monday - Friday, excluding US Holidays. Our goal is to respond to your inquiry within 3 business days. Please note that it may take longer depending on current volume.

**Comment by Linkerss** [comment]
Recently I've tried to add one of Twitter feeds to your Heroku App. The feed was unbearably slow and almost unusable.

As long as we can Deploy your App to Heroku it's still good in my opinion :)

**Comment by stefansundin** [comment]
My account was unsuspended a few hours after it happened. I finally received an explanation that it was related to an incident on Heroku's end where they accidentally suspended a bunch of accounts. That's a pretty crappy thing to happen, but it sounds like it was an honest mistake.

https://status.heroku.com/incidents/2386

![Screen Shot 2021-11-28 at 23 12 25](https://user-images.githubusercontent.com/1991151/143823747-9ea7f944-758c-4208-99a4-300ad38d5743.png)
