### ISSUE TITLE
Increase the number of fetched Twitter posts

### ISSUE THREAD

**Issue by kia0007** [stefansundin/rssbox#59]
I know that it increases the pressure on the server but i need to fetch all tweets of couple of twitter accounts

**Comment by stefansundin** [comment]
Hello.

You can fork the project and increase the number here: https://github.com/stefansundin/rssbox/blob/e6ee86f04b4f29f551da9477b831c06e27cde8b9/app.rb#L186

I believe you can fetch at most 200 tweets at a time. I haven't implemented a way to fetch older tweets, so at the moment there's unfortunately no easy way to "fetch all tweets".

**Comment by kia0007** [comment]
I don't own a server nor do i have knowledge about coding. Is it possible for me to do that?

**Comment by stefansundin** [comment]
Probably not. Sorry.
