### ISSUE TITLE
Twitter with media returns only one tweet

### ISSUE THREAD

**Issue by jlitz** [stefansundin/rssbox#60]
Twitter with media returns only one tweet seems very delayed vs twitter site    server problem i suppose

**Comment by stefansundin** [comment]
This filter is applied after the tweets have been retrieved from Twitter. So if the user has only posted one tweet with media in their last 100 tweets, then that's the reason you only see a single one.

There shouldn't be any delay.

https://github.com/stefansundin/rssbox/blob/1aa571f753d197237968d4e19fa2f3bd7dfd9ae6/app.rb#L259-L265

**Comment by jlitz** [comment]
Hi, 
This is my twitter feed https://twitter.com/jlitwinetz   I make a lot  of posts using microsoft flow  news  and reddit feeds and most contain media.   Fwiw.   I am trying out various  RSS readers  Feedbro seems very good.  Fluent,  Ow., and Bazquz. all show delays  maybe 35 min vs my feed in a browser .      Just passing along what I see.   Very nice app fills a void.

**Comment by stefansundin** [comment]
RSS Box does cache feeds for a while so that's probably why you see the delay. This happens to all feeds and is unrelated to the "with media" option.

**Comment by jlitz** [comment]
Ok  Tnx.
