### ISSUE TITLE
rssbox.herokuapp.com will stop working on November 28th (Heroku is shutting down their free tier)

### ISSUE THREAD

**Issue by stefansundin** [stefansundin/rssbox#61]
https://blog.heroku.com/next-chapter

> Starting October 26, 2022, we will begin deleting inactive accounts and associated storage for accounts that have been inactive for over a year. Starting November 28, 2022, we plan to stop offering free product plans and plan to start shutting down free dynos and data services. We will be sending out a series of email communications to affected users.

It is the end of an era for RSS Box! Heroku has been great for a long time, but I think it is time to move on. RSS Box has managed to run on the free tier despite receiving some impressive traffic over the years. I made the app publicly available without requiring users to register an account because I wanted to see how well I could make it run. The app has gone down at times because of the load but it has always come back.

I think I have only received one or two donations for RSS Box, so there is no way that I would ever start paying for Heroku. I recommend that everyone switches off of the domain as soon as possible. It is likely that someone else might be able to take over the domain after November 28th, so to avoid getting advertisements or similar in your RSS feeds, please move your subscriptions! The only way I would start paying would be if someone else would donate enough money to keep it running there. Even in that case I would request that you donate that money to me instead so that I can run it somewhere else instead (Heroku is quite expensive compared to other hosting services).

If any of you is hosting your own RSS Box on Heroku and you are considering paying then please: **deploy the latest version of the code and remove the Redis addon**. It is no longer required and you don't want to pay for something that isn't needed.

About four years ago I launched a second version of RSS Box on Elastic Beanstalk. You can access it here: https://rssbox.us-west-2.elasticbeanstalk.com/. I am paying for this but I have optimized the costs to a level that is acceptable for me, at least for the time being. You can move your subscriptions to this domain if you want, but I can't guarantee how long I will keep it. I dislike Elastic Beanstalk for many reasons so I will probably get rid of this eventually. There will be more frequent downtime than Heroku.

I have experimented with running RSS Box in Kubernetes but that is far too complicated to set up for most users, and I will probably never offer a public version hosted like this. I have also experimented running it on Amazon ECS and I think it is likely that I will use this to replace the Elastic Beanstalk version. I need to make some improvements first though because I would like to offer HTTPS without the need of an expensive load balancer.

So this is the unfortunate news that I wanted to share. If you want to use RSS Box in a way that will last then I recommend that you self-host it.

In the last week or so before November 28th, I may deploy a special version of the app that simply replaces all feeds with a single entry that contains a deprecation message. I will put a warning on the website for now.

If you want to donate to support RSS Box then the easiest option is to use PayPal using this link: https://www.paypal.com/donate/?cmd=_donations&business=KYMVEK692RF5Q&item_name=RSS+Box&no_shipping=1

I am interested in getting a rough sense of how the community is self-hosting it. What platform are you using? Feel free to share your experience in the comments below!

Thanks!

P.S. I never used a custom domain for the Heroku app since that would mean I would have to pay extra for HTTPS. I'm not using it for Elastic Beanstalk even though I could, but I am not sure that I want to. I will be forced to do it for ECS if I spin that up, so at that point I may offer a domain that is more stable and will survive replatforming.

**Comment by Linkerss** [comment]
Any chance you add Twitter hashtags feature before you close down so we can self Host it? It's an awesome App,

Thank you for your great work

**Comment by stefansundin** [comment]
Hi Linkerss. I will not stop developing RSS Box just because the Heroku app is being shut down. I know you requested Instagram hashtag feature in #27 but I haven't really felt like it is something that I want yet which is why I haven't worked on it. Let's try to keep this issue on topic. Thanks!

**Comment by Linkerss** [comment]
Obviously Instagram feeds doesn't work even if you added hashtags feature. Now I need Twitter hashtags. Many people use hashtags feeds, Not sure why you're not adding it if we can self Host it?

Glad you won't stop developing the App,

Thank you

**Comment by GommeDank** [comment]
I must admit I've never donated... Don't you think you could try to save your instance by trying to launch a donation campaign ? Anyway, thanks for your work.

**Comment by stefansundin** [comment]
I could keep it up on Heroku for about $7 per month. So if anyone wants to extend the life of that domain then this is one option. But I don't think this is the best use of donation money. I am running the app on Elastic Beanstalk with comparable performance and I pay about $1.50 per month. So for the same money I can run it there almost 5 times as long. :)

As I stated above, I have grown to dislike Elastic Beanstalk so my plan is to eventually move away from that, probably to Amazon ECS. This will have comparable costs, maybe a tiny bit more expensive.

**Comment by GommeDank** [comment]
I don't think I could run my own rssbox. Whatever you're going to do, I can donate.

**Comment by stefansundin** [comment]
I will do my best to keep at least one public version of RSS Box online, even if no one donates. I might move this over time so I can't promise that the domain name stays the same. Currently the best option is to subscribe to the Elastic Beanstalk domain: https://rssbox.us-west-2.elasticbeanstalk.com/

However, if you want to donate then there is no need to wait until Heroku shuts down the application. If you want to donate specifically to keep the Heroku domain going then please specify this along with your donation.

If you don't specify that you want to keep the Heroku domain going then I will allocate the money to the most cost-efficient option (which currently is the Elastic Beanstalk server).

You can either use the donation form on the RSS Box website, or use this link: https://www.paypal.com/donate/?cmd=_donations&business=KYMVEK692RF5Q&item_name=RSS+Box&no_shipping=1

Thanks for everyone who decides to donate!

**Comment by eyoungmin** [comment]
I am always grateful to you. It's my favorite way to get an Instagram RSS feed.
It's easy to install with the Heroku button. Your guide is kind. I'm not a developer, but I could easily install it. All I had to do was put in environmental variables. My head started to hurt as Heroku ended the free plan.

Can I self-host again with the lowest possible price? I'd like an easy guide.
My activities will interfere with your free service. I want to self-host .

I want to take the initiative in getting information. The algorithm of social media makes me tired.

**Comment by stefansundin** [comment]
My head is hurting as well. 😵‍💫

I will try to write up some instructions for easier self-hosting. I think fly.io might be the simplest/best free service to transition over to. One reason why I didn't look into that service earlier is because I'd rather look into paid options that I can make very cheap and keep forever. There is no telling how long fly will keep their free plan around. But at the same time, setting up AWS services is not very user friendly so I think that might put a lot of people off from attempting to self-host. I should aim to support multiple options and at least one of them should be as easy as Heroku has been.

Having said all that, I have created https://rssbox.fly.dev/. I haven't configured any API keys yet, I mostly wanted to reserve the domain. I'll fine-tune it later.

It appears that fly offers 3 GB of persistent volume on the free plan, which would be great to keep the file cache around across restarts and deployments. That's one problem the Heroku app has always suffered from, when it restarts (which it does at least once a day) it loses all the cache and becomes very slow for a while.

**Comment by stefansundin** [comment]
I have created a discussion where people can see what public RSS Box instances I provide, and it is also a place where you can share your own public instance if you'd like. Please have a look here: https://github.com/stefansundin/rssbox/discussions/64

I'm going to start dismantling rssbox.herokuapp.com now. I will deploy a special version that replaces all feeds with a notice that will contain a link to the discussion above.

**Comment by stefansundin** [comment]
I just did the final shut down work on the Heroku app. It now shows the Heroku maintenance page. I don't know if this will continue working but I hope so. The risk is that Heroku deletes my account at some point which may allow anyone to grab that domain later, and potentially serve ads in the feeds. That's not great but there's nothing I can do about it.
