### ISSUE TITLE
Twitter API is becoming paid soon

### ISSUE THREAD

**Issue by stefansundin** [stefansundin/rssbox#66]
https://twitter.com/TwitterDev/status/1621026986784337922

I was fearing that this would happen eventually.. this is Instagram all over again.

As far as I can tell there's no information yet on exactly how much the paid access will cost, or how much quota you get.

Since Instagram isn't working anymore, Twitter is by far the most used service on my public instance. I know that some people donated to keep the public instance around after Heroku shut down their free tier. I'm willing to use those funds to keep Twitter going, **if the pricing is reasonable** ([press X to doubt](https://knowyourmeme.com/memes/la-noire-doubt-press-x-to-doubt)).

Please feel free to discuss here.

On related news.. maybe I should start looking into how the Mastodon network works?

**Comment by jutsh65** [comment]
Haven't seen the official source yet, but it looks like around $2,500 a month for 10k requests.

I follow about 10 accounts, updated once an hour each day comes to 7,200 requests. Assuming one request and no overhead. 

https://techhub.social/@Sephsekla@mastodon.lol/109796375142493045

Oh well, so much for my twitter follows. If it isn't on rss it is dead to me.

**Comment by stefansundin** [comment]
That source seems unreliable to me. It looks like it is specifically for the Search API which I believe has been around for a long time. I don't think this is what they will go with, but you never know.

**Comment by stefansundin** [comment]
So it looks like the magic number is $100/month. https://twitter.com/TwitterDev/status/1623467617037221889

The donations I received will pay for about one month then. 😂 So that's pretty much off the table.

There's also another tweet saying there will still be a free version, but probably extremely limited. No real details though. https://twitter.com/TwitterDev/status/1623467618400374784

There are also ways to effectively use the API without an actual client app, but who knows if this will continue working. Wouldn't be surprised if they manage to block this similar to what Instagram is doing. https://github.com/Rishikant181/Rettiwt-API

I think I'll just keep it the way it is until the feeds stop working, then I'll consider the available options.

**Comment by stefansundin** [comment]
Delayed again lol. https://twitter.com/TwitterDev/status/1625234161010343941

**Comment by stefansundin** [comment]
https://twitter.com/TwitterDev/status/1641222782594990080

> Introducing a new form of Free (v2) access for write-only use cases and those testing the Twitter API with 1,500 Tweets/month at the app level, media upload endpoints, and Login with Twitter.

Not interested.

> We are also launching a new Basic (v2) access for hobbyists with 10,000 GET/month and 50,000 POST/month, 2 app IDs, and Login with Twitter for $100/month.

$100/month to make 10,000 read requests 🤣

> Over the next 30 days, we will deprecate current access tiers such as Standard (v1.1), Essential (v2), Elevated (v2), and Premium so we recommend that you migrate to the new tiers as soon as possible for a smooth transition.

We'll see if they keep to that timeline or not. I'm not going to touch any code until things are completely broken and the API is returning errors. It sounds like the new paid API requires API v2? Weird. Is this going to completely kill v1.1?

Anyway, no way I'm spending $100/month on this.

**Comment by stefansundin** [comment]
😢

![](https://user-images.githubusercontent.com/1991151/230466605-26f43ebb-c9e4-431c-a831-058aa3aeecec.png)

**Comment by stefansundin** [comment]
Here's two interesting graphs on the load on the rssbox.fly.dev instance when the Twitter API was shut down:

![Screenshot 2023-04-15 at 17 37 41](https://user-images.githubusercontent.com/1991151/232260112-4bf66059-0890-4eb3-9f01-3b5cb0790f56.png)
![Screenshot 2023-04-15 at 17 37 49](https://user-images.githubusercontent.com/1991151/232260114-376f0df2-e897-423c-a3ad-8f1bdeaf0001.png)

**Comment by zymsbgt** [comment]
Regarding RSS for Mastodon, I came across this article recently, I hope it helps!
https://fedi.tips/following-mastodon-and-fediverse-accounts-through-rss/

**Comment by stefansundin** [comment]
RIP Twitter.
