### ISSUE TITLE
RSS unaltered titles entries

### ISSUE THREAD

**Issue by sn-o-w** [stefansundin/rssbox#9]
Hey there. Is it possible to have unaltered titles entries?

E.g., for YouTube (maybe other services too?) to have two tags like < original-title > and < title > for the entries within a feed? I don't really need the duration of a livestream and "(started)"/"(completed)". If your awesome RSSbox will show me original titles as well, that would be nice.

**Comment by stefansundin** [comment]
Hi!

There is no way to opt-out of this at the moment. Most RSS readers support the native YouTube feeds, e.g. https://www.youtube.com/feeds/videos.xml?channel_id=UCkIfUg5-SkgtXXLqOAjiWsA

These feeds are cleaner and might be what you are looking for. RSSBox will take you to these feeds if you use the normal submit button and not the _Live_ item in the dropdown.

Since you are asking for a non-standard tag such as `<original-title>`, it makes me think you are programmatically parsing the feed?

**Comment by cristisilaghi** [comment]
Yeah, I know. But YouTube's normal and default RSS is sometimes stupid and doesn't show the current livestreams a/o videos uploaded.

Using your "Live" thing for YouTube is working well, but I would like to have the original title, not an altered one. Having two tags like < original-title > and < title > would help me to choose which one I need (I use a RSS bot and I prefer the original title for the entries of the feed). Or let it be just <title> showing original title and nothing else added to it.

**Comment by stefansundin** [comment]
I created a branch for you with the change you want. https://github.com/stefansundin/rssbox/tree/cristisilaghi

You can create your own Heroku app that runs it if you do the following:
- Create Heroku account. https://www.heroku.com/
  - You can host one app for free.
- Create Google developer project, enable the YouTube API, and get an API key. See https://github.com/stefansundin/rssbox#google
- Click this link to deploy the branch: https://heroku.com/deploy?template=https://github.com/stefansundin/rssbox/tree/cristisilaghi
  - Input your Google API key in the `GOOGLE_API_KEY` field.

Anyway, you can fork the repo and do whatever you want, and deploy changes to your own Heroku app.

I don't know what RSS bot you are using, but perhaps it is simpler to just have it query the YouTube API directly. It may be even easier. Basically all the code you need to look at are these lines: https://github.com/stefansundin/rssbox/blob/a2977bad4562ea1726bb899b44572564a319f534/app.rb#L237-L264

**Comment by cristisilaghi** [comment]
I use Discord.RSS on several Discord servers. And I can customize the feed's text message, I can choose which tags I need, what info to display.

I had a look at YT API v3, but it seems it doesn't work as RSS. And default YT's RSS is not working well. As I said earlier, YT's RSS sometimes will not publish new video/livestreams.
